  storage:
    directories:
      - filesystem: "root"
        path: "/opt/bin"
        mode: 0755
      - filesystem: "root"
        path: "/opt/cni/bin"
        mode: 0755
      - filesystem: "root"
        path: "/etc/kubernetes/pki/etcd"
        mode: 0755 
      - filesystem: "root"
        path: "/etc/kubernetes/pki/calico"
        mode: 0755
      - filesystem: "root"
        path: "/opt/scripts"
        mode: 0755
    files: 
      - filesystem: "root"
        path: "/opt/scripts/make-scratch.sh"
        mode: 0755
        contents: 
          local: "make-scratch.sh"
      - filesystem: "root"
        path: "/etc/systemctl.d/nonlocalbind.conf"
        mode: 0644 
        contents:
          inline: net.ipv4.ip_nonlocal_bind=1
  systemd:
    units:
      - name: "locksmithd.service"
        mask: true
      - name: "update-engine.service"
        enabled: true
      - name: "create-ephemeral.service"
        enabled: true
        contents: | 
          [Unit]
          Description=Create ephemeral disk
          After=kubelet.servic
          [Service]
          Type=oneshot
          ExecStart=/opt/scripts/make-scratch.sh
          [Install]
          WantedBy=multi-user.target
      - name: "docker.service"
        enabled: true
        contents: |
          [Unit]
          Description=kubelet: The Kubernetes Node Agent
          Documentation=http://kubernetes.io/docs/
          [Service]
          ExecStartPre=/usr/bin/mkdir -p /etc/cni/net.d
          ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
          ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
          ExecStartPre=/usr/bin/mkdir -p /var/log/containers
          ExecStart=/opt/bin/kubelet
          Restart=always
          StartLimitInterval=0
          RestartSec=10
          [Install]
          WantedBy=multi-user.target
        dropins:
          - name: "10-kubeadm.conf"
            contents: |
              [Service]
              Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
              Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --serialize-image-pulls=false"
              Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
              Environment="KUBELET_DNS_ARGS=--cluster-dns=10.255.99.10 --cluster-domain=cluster.local"
              Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
              Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"
              Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
              Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true"
              ExecStart=
              ExecStart=/opt/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
